name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Build lib
      run: npm build-lib-ci
      
    - name: Run Tests
      run: npm run test-ci
